### ISSUE TITLE
מועדפים לא נפתח - עם ERROR 

### ISSUE THREAD

**Issue by rafi-d** [Fishenzon/repo#123]
אני מנסה לפתוח את המועדפים ולא יכול... הנה הLOG יש מצב שתוכל לעזור "להנציל" את המועדפים שלי? תודה!
מערכת: אנדרואיד 9, קודי 18.9 

```
2022-03-01 22:54:40.936 T:19356   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.NameError'>
                                            Error Contents: global name 'iconimage' is not defined
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.idanplus/default.py", line 5, in <module>
                                                route(argv[2])
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.idanplus/resources/main.py", line 370, in route
                                                ShowFavorties()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.idanplus/resources/main.py", line 228, in ShowFavorties
                                                common.addDir(name, "toggleSortingMethod", 15, iconimage, {"Title": name, "Plot": "{0}[CR]{1}[CR]{2} / {3}".format(name, common.GetLocaleString(30004), common.GetLocaleString(30036), common.GetLocaleString(30003))}, isFolder=False)
                                            NameError: global name 'iconimage' is not defined
                                            -->End of Python script error report<--
2022-03-01 22:54:40.947 T:10366  NOTICE: Trying to open: samplerate: 44100, channelMask: 12, encoding: 4
2022-03-01 22:54:40.960 T:10366  NOTICE: CAESinkAUDIOTRACK::Initializing with: m_sampleRate: 44100 format: AE_FMT_FLOAT (AE) method: PCM stream-type: PCM-STREAM min_buffer_size: 30208 m_frames: 1888 m_frameSize: 8 channels: 2
2022-03-01 22:54:41.311 T:19355   ERROR: GetDirectory - Error getting plugin://plugin.video.idanplus/?iconimage=%252Fstorage%252Femulated%252F0%252FAndroid%252Fdata%252Forg.xbmc.kodi%252Ffiles%252F.kodi%252Faddons%252Fplugin.video.idanplus%252Ficon.png&mode=10&module&moredata&name=%5bB%5d%d7%9e%d7%95%d7%a2%d7%93%d7%a4%d7%99%20%d7%a2%d7%99%d7%93%d7%9f%20%d7%a4%d7%9c%d7%95%d7%a1%5b%2fB%5d&url
2022-03-01 22:54:41.329 T:10357   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.idanplus/?iconimage=%252Fstorage%252Femulated%252F0%252FAndroid%252Fdata%252Forg.xbmc.kodi%252Ffiles%252F.kodi%252Faddons%252Fplugin.video.idanplus%252Ficon.png&mode=10&module&moredata&name=%5bB%5d%d7%9e%d7%95%d7%a2%d7%93%d7%a4%d7%99%20%d7%a2%d7%99%d7%93%d7%9f%20%d7%a4%d7%9c%d7%95%d7%a1%5b%2fB%5d&url) failed
 

```

**Comment by rafi-d** [comment]
במחשבה שניה - אולי אחד הלינקים ששםהוסר מהאתר, והתוסף לא מטפל טוב בהסרה טוטומטית גם מהמועדפים?

**Comment by rafi-d** [comment]
ניסיתי למחוק את כל הקבצים של התוסף  בuserdata ולעבור לגרסה קודמת - שני הדברים לא עזרו :(

**Comment by Fishenzon** [comment]
בוקר טוב.
נסה את גירסה 3.1.1

**Comment by rafi-d** [comment]
עובד, תודה! 
מה היה? משהו ספציפי לקודי 18 שאצלי?

**Comment by Fishenzon** [comment]
זה היה עוזר זמנית,
