### ISSUE TITLE
VOD  כאן11  ב1080 ?

### ISSUE THREAD

**Issue by rafi-d** [Fishenzon/repo#32]
אפשר להוסיף בדפדפן יכולת בחירה של איכות לVOD של ערוץ 11? 
להבנתי כול החומר מאוחסו ב
YOUTUBE, ושם האיכות היא עד 1080P
אולי להוסיף בחירה כמו בערוץ החי?

אגב, תוכל להזכיר לי - מה נדרש לקנפג בקודי מבחינת YOUTUNE כדי שזה יעבוד בתוסף? 
ההרחבה של YOUTUBE מוציאה לי שגיעה.

http://www.imagebam.com/image/6009211185986434

עריכה:
אני רואה שבאנדרואיד 1080P זה הדיפולט...

**Comment by rafi-d** [comment]
השגיאה שאני רואה:

17:29:49.069 T:8704   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named moves.http_client
                                            Traceback (most recent call last):
                                              File "D:\Program Files\Kodi\portable_data\addons\plugin.video.youtube\resources\lib\default.py", line 11, in <module>
                                                from youtube_plugin.kodion import runner
                                              File "D:\Program Files\Kodi\portable_data\addons\plugin.video.youtube\resources\lib\youtube_plugin\kodion\__init__.py", line 21, in <module>
                                                from .impl import Context
                                              File "D:\Program Files\Kodi\portable_data\addons\plugin.video.youtube\resources\lib\youtube_plugin\kodion\impl\__init__.py", line 12, in <module>
                                                from .xbmc.xbmc_context import XbmcContext as Context
                                              File "D:\Program Files\Kodi\portable_data\addons\plugin.video.youtube\resources\lib\youtube_plugin\kodion\impl\xbmc\xbmc_context.py", line 24, in <module>
                                                from ..abstract_context import AbstractContext
                                              File "D:\Program Files\Kodi\portable_data\addons\plugin.video.youtube\resources\lib\youtube_plugin\kodion\impl\abstract_context.py", line 17, in <module>
                                                from ..utils import *
                                              File "D:\Program Files\Kodi\portable_data\addons\plugin.video.youtube\resources\lib\youtube_plugin\kodion\utils\__init__.py", line 19, in <module>
                                                from .http_server import get_http_server, is_httpd_live, get_client_ip_address
                                              File "D:\Program Files\Kodi\portable_data\addons\plugin.video.youtube\resources\lib\youtube_plugin\kodion\utils\http_server.py", line 17, in <module>
                                                import requests
                                              File "D:\Program Files\Kodi\portable_data\addons\script.module.requests\lib\requests\__init__.py", line 43, in <module>
                                                import urllib3
                                              File "D:\Program Files\Kodi\portable_data\addons\script.module.urllib3\lib\urllib3\__init__.py", line 8, in <module>
                                                from .connectionpool import (
                                              File "D:\Program Files\Kodi\portable_data\addons\script.module.urllib3\lib\urllib3\connectionpool.py", line 11, in <module>
                                                from .exceptions import (
                                              File "D:\Program Files\Kodi\portable_data\addons\script.module.urllib3\lib\urllib3\exceptions.py", line 2, in <module>
                                                from .packages.six.moves.http_client import (
                                            ImportError: No module named moves.http_client
                                            -->End of Python script error report<--
17:29:49.090 T:10004   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.idanplus/?moredata=best&name=%5BCOLOR+yellow%5D%D7%A4%D7%A8%D7%A7+13+%7C+%D7%A0%D7%98%D7%9C+%D7%94%D7%94%D7%95%D7%9B%D7%97%D7%94%5B%2FCOLOR%5D&url=https%253A%252F%252Fwww.youtube.com%252Fembed%252FqHN-DJLjrjI&iconimage=https%253A%252F%252Fkanweb.blob.core.windows.net%252Fdownload%252Fpictures%252F2019%252F2%252F26%252Fimgid%253D5423_A.png&module=kan&mode=3]

**Comment by Fishenzon** [comment]
כל ההגדרות קשורות רק ליוטיוב ול-InputStream.Adaptive.
זה לא בשליטה של ההרחבה.
![screenshot000](https://user-images.githubusercontent.com/29551534/55679873-71381280-591b-11e9-8a38-24c36de0808f.png)
![screenshot001](https://user-images.githubusercontent.com/29551534/55679874-71381280-591b-11e9-8439-eb99748d8b4b.png)
![screenshot002](https://user-images.githubusercontent.com/29551534/55679875-71381280-591b-11e9-9eb7-e659f2529970.png)

![screenshot004](https://user-images.githubusercontent.com/29551534/55679942-0fc47380-591c-11e9-9c5e-d7db0442017b.png)

**Comment by rafi-d** [comment]
אכן, עובד בקודי 17.6
ב18.0 לא. עובד לך גם שם?

**Comment by Fishenzon** [comment]
כמובן, התמונות צולמו בקודי 18.1

**Comment by rafi-d** [comment]
אז כנראה בעיה מקומית בהתקנה שלי, כי אני לא מסוגל אפילו לראות את תוכן הVOD...

**Comment by rafi-d** [comment]
OK, 
  עדכנתי לגרסה 18.1
ונראה שהכל תקין
תודה
