### ISSUE TITLE
בעיה (מקומית כנקרה) בהפעלת התוסף בקודי 17.6 WIN10

### ISSUE THREAD

**Issue by rafi-d** [Fishenzon/repo#37]
היי
נתקלתי פתאום בבעיה מקומית כשהפעלת התוסף פשוט מכשלת (לא מופיע התפריט)
כנראה שעדכנתי את אחד התוספים האחרים בקודי ואז התחילה הבעיה.
תוכל להציץ ב
LOG של הטעויות, ואולי להבין מה מקור הבעיה?

23:31:58.160 T:6068   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'module' object has no attribute 'Message'
                                            Traceback (most recent call last):
                                              File "D:\Program Files\Kodi\portable_data\addons\plugin.video.idanplus\default.py", line 4, in <module>
                                                import resources.lib.common as common
                                              File "D:\Program Files\Kodi\portable_data\addons\plugin.video.idanplus\resources\lib\common.py", line 3, in <module>
                                                import sys, gzip, os, io, random, re, json, urllib, urllib2, urlparse, time, collections, xml.parsers.expat as expat
                                              File "D:\Program Files\Kodi\system\python\Lib\urllib2.py", line 94, in <module>
                                                import httplib
                                              File "D:\Program Files\Kodi\system\python\Lib\httplib.py", line 255, in <module>
                                                class HTTPMessage(mimetools.Message):
                                            AttributeError: 'module' object has no attribute 'Message'
                                            -->End of Python script error report<--
23:31:58.767 T:3924  NOTICE: AddOnLog: PVR IPTV Simple Client: EPG Loaded.
23:33:13.794 T:12100   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'module' object has no attribute 'Message'
                                            Traceback (most recent call last):
                                              File "D:\Program Files\Kodi\portable_data\addons\plugin.video.idanplus\default.py", line 4, in <module>
                                                import resources.lib.common as common
                                              File "D:\Program Files\Kodi\portable_data\addons\plugin.video.idanplus\resources\lib\common.py", line 3, in <module>
                                                import sys, gzip, os, io, random, re, json, urllib, urllib2, urlparse, time, collections, xml.parsers.expat as expat
                                              File "D:\Program Files\Kodi\system\python\Lib\urllib2.py", line 94, in <module>
                                                import httplib
                                              File "D:\Program Files\Kodi\system\python\Lib\httplib.py", line 255, in <module>
                                                class HTTPMessage(mimetools.Message):
                                            AttributeError: 'module' object has no attribute 'Message'
                                            -->End of Python script error report<--
23:36:58.468 T:3924  NOTICE: AddOnLog: PVR IPTV Simple Client: EPG Loaded.
23:48:58.489 T:4048  NOTICE: Previous line repeats 2 times.
23:48:58.489 T:4048   ERROR: XFILE::CDirectory::GetDirectory - Error getting None
23:49:06.538 T:8548   ERROR: Previous line repeats 3 times.
23:49:06.539 T:8548   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'module' object has no attribute 'Message'
                                            Traceback (most recent call last):
                                              File "D:\Program Files\Kodi\portable_data\addons\plugin.video.idanplus\default.py", line 4, in <module>
                                                import resources.lib.common as common
                                              File "D:\Program Files\Kodi\portable_data\addons\plugin.video.idanplus\resources\lib\common.py", line 3, in <module>
                                                import sys, gzip, os, io, random, re, json, urllib, urllib2, urlparse, time, collections, xml.parsers.expat as expat
                                              File "D:\Program Files\Kodi\system\python\Lib\urllib2.py", line 94, in <module>
                                                import httplib
                                              File "D:\Program Files\Kodi\system\python\Lib\httplib.py", line 255, in <module>
                                                class HTTPMessage(mimetools.Message):
                                            AttributeError: 'module' object has no attribute 'Message'
                                            -->End of Python script error report<--
23:49:06.574 T:10528   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.idanplus/
23:49:06.653 T:10528   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.idanplus/) failed
23:

תודה

רפי

**Comment by Fishenzon** [comment]
לפי מה שכתוב, נראה שיש לך בעיה ברכיבים פנימיים של פייתון:
urllib2.py או יותר נכון httplib
אני הייתי פשוט מתקין מחדש את קודי, בלי למחוק את מה שיש, ככה שיכול להיות שזה יתקן לך את מה שנפגם.

**Comment by rafi-d** [comment]
בדקתי, הקבצים זההים להתקנה המקורית. 
מרגיש כמו אי התאמה בגירסאות של איזו סקריפט/תוסף :(

**Comment by Fishenzon** [comment]
תצטרך למצוא מה גורם לזה, אם לא, יכולה להיות לך בעיה בהרחבות נוספות.
בכל מקרה, התקלה מקומית.

**Comment by rafi-d** [comment]
אכן, אלא אם התוסף עצמו (כמו תוספים אחרים) לא תומך בגרסה מסויימת של סקריפט למשל

**Comment by Fishenzon** [comment]
אתה מדבר על קודי 17.6 ואומר שההרחבה עבדה לך.
השגיאה שמתקבלת מצביעה על בעיה בפייטון עצמו.
משהו נדפק לך שם.
תמחק הכל ותתקין מחדש.

**Comment by rafi-d** [comment]
נכון, ברור לי שזה משהו שקרה לי ... קצת מתעצל להתקין שוב תוספים אחרי ההתקנה המקורית. בלית ברירה - נעשה זאת (אגב, באנדרואיד הייתה לי בעיה בסגנון דומה, לא בתוסף עידן,  ושם פתרתי ע"י חזרה אחורה בגירסה של אחד הסקריפטים שהתעדכן אוטומטית).

**Comment by Fishenzon** [comment]
בהצלחה

**Comment by rafi-d** [comment]
לא תאמין מה פתר את הבעייה... 
מחקתי את כל מאות קבצי ה *.pyo 
תחת כל המחיצה של ההתקנה... 

לך תבין מה קרה.. 

תודה על העזרה :)
